monolog:
    handlers:
        game:
            type: rotating_file
            path: '%kernel.logs_dir%/game.log'
            level: debug
            channels: ['user', 'game', 'gunslinger']
            max_files:  7
        update_handler:
            type: rotating_file
            path: '%kernel.logs_dir%/update_handler.log'
            level: debug
            channels: ['update_handler']
            max_files:  7
    channels:
        - 'game'
        - 'gunslinger'
        - 'update_handler'
        - 'user'
