version: '3.4'
services:
    php:
        build:
            context: ./docker/php
            target: production
            args:
                - TZ
                - UID
                - GID
        container_name: nagan_bot_php
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/conf.d/php-${APP_ENV}.ini:/usr/local/etc/php/conf.d/php.ini:ro
        depends_on:
            - mysql

    mysql:
        image: mariadb:10.5
        container_name: nagan_bot_mysql
        restart: always
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
            - ./docker/mysql/database:/var/lib/mysql
        environment:
            - TZ
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE

    nginx:
        image: nginx:1.17-alpine
        container_name: nagan_bot_nginx
        restart: always
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php
