version: '3.7'
services:
    app:
        depends_on:
            - db
    db:
        image: mariadb:11
        container_name: naganbot_db
        restart: on-failure
        ports:
            - $DB_PORT:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=app
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
volumes:
    db_data:
        name: naganbot_db_data
