version: '3.7'
services:
    mysql:
        image: keinos/sqlite3:3
        container_name: naganbot_sqlite
        volumes:
            - sqlite_workspace:/workspace
        ports:
            - $MYSQL_EXPOSE_PORT:3306
        environment:
            - MYSQL_DATABASE
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - TZ
        restart: always
volumes:
    sqlite_workspace:
        name: naganbot_sqlite_workspace
