imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Twig\Strategy\Escaper\EscaperStrategyInterface:
            tags: ['app.twig.strategy.escaper']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Constant/'
            - '../src/Entity/'
            - '../src/Exception/'
            - '../src/Event/'
            - '../src/ValueObject/'
            - '../src/Kernel.php'

    App\Manager\Game\GameManager:
        arguments:
            $numberOfPlayers: '%app.game.number_of_players%'

    App\DependencyInjection\Configurator\Twig\EnvironmentConfigurator:
        decorates: 'twig.configurator.environment'
        arguments:
            $strategiesGenerators: [!tagged app.twig.strategy.escaper]
