imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Constant/'
            - '../src/Entity/'
            - '../src/Exception/'
            - '../src/Event/'
            - '../src/ValueObject/'
            - '../src/Kernel.php'

    App\Manager\Game\GameManager:
        arguments:
            $numberOfPlayers: '%app.game.number_of_players%'
