imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }
        arguments:
            $exceptionLogger: '@monolog.logger.exception'

    App\Manager\GameManager:
        arguments:
            $numberOfPlayers: '%app.game.number_of_players%'
