package translator

var GameTranslations = translations{
	"ru": {
		"something went wrong": {message: SimpleMessage("Наган заклинило. Мы уже вызвали оружейника.")},
		"game creation": {
			oneOf: []oneOf{
				{message: SimpleMessage("Мы играем чтобы пощекотать нервы, хочешь тоже?")},
				{message: SimpleMessage("Я вижу ты не из трусливых, что насчёт остальных?")},
				{message: SimpleMessage("Вы опять за старое? Так уж и быть")},
				{message: SimpleMessage("Ну что, рискнёте сыграть в игру с летальным исходом?")},
				{message: SimpleMessage("Смерть или слава? Давайте узнаем!")},
				{message: SimpleMessage("Кто-то сегодня не вернётся домой...")},
				{message: SimpleMessage("Пистолет заряжен, очередь за вами.")},
				{message: SimpleMessage("Русская рулетка — лучший способ проверить удачу.")},
				{message: SimpleMessage("Готовы испытать судьбу?")},
				{message: SimpleMessage("Один выстрел — и ты в истории.")},
				{message: SimpleMessage("Судьба любит смелых. Или нет?")},
				{message: SimpleMessage("На кону жизнь. Ну, почти.")},
				{message: SimpleMessage("Ну что, кто сегодня испытывает удачу?")},
				{message: SimpleMessage("Барабан пуст... Пока что.")},
				{message: SimpleMessage("Ставки сделаны. Осталось нажать на курок.")},
				{message: SimpleMessage("Сейчас выясним, кто любимчик удачи.")},
				{message: SimpleMessage("Открываем сезон плохих решений.")},
			},
		},
		"joining the game": {
			oneOf: []oneOf{
				{message: SimpleMessage("Могу поспорить, что ты - труп")},
				{message: SimpleMessage("Ты считаешь себя бессмертным?")},
				{message: SimpleMessage("Ну хорошо, присаживайся, игра скоро начнётся")},
				{message: SimpleMessage("Решил напоследок рискнуть?")},
				{message: SimpleMessage("1 к 6 - вот твой шанс выживания в русской рулетке")},
				{message: SimpleMessage("Здесь произойдёт охуенное убийство")},
				{message: SimpleMessage("Ты играл когда-нибудь до этого в рулетку?")},
				{message: SimpleMessage("Добро пожаловать в клуб самоубийц.")},
				{message: SimpleMessage("Шанс выжить? Примерно как у снега в аду.")},
				{message: SimpleMessage("Ты либо герой, либо покойник.")},
				{message: SimpleMessage("Один патрон, шесть камер. Удачи.")},
				{message: SimpleMessage("Ты уверен, что хочешь это сделать?")},
				{message: SimpleMessage("Сейчас узнаем, насколько ты везучий.")},
				{message: SimpleMessage("Ты либо выйдешь победителем, либо станешь уроком для остальных.")},
				{message: SimpleMessage("Ну что, готов к своему последнему клику?")},
				{message: SimpleMessage("Судьба улыбается... или нет?")},
				{message: SimpleMessage("Ещё один доброволец.")},
				{message: SimpleMessage("Смелость или отсутствие инстинкта самосохранения?")},
				{message: SimpleMessage("Стул свободен, револьвер тоже.")},
				{message: SimpleMessage("Похоже, статистика сегодня пополнится.")},
				{message: SimpleMessage("Добро пожаловать. Назад только вперёд ногами.")},
			},
		},
		"play the game": {
			oneOf: []oneOf{
				{
					allOf: []oneOf{
						{message: SimpleMessage("Решили рискнуть? Тогда начнём")},
						{message: SimpleMessage("Стопка, щелчок, выстрел...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Хорошо, раз все в сборе, начнём")},
						{message: SimpleMessage("Пистолет передаётся следующему...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Игра началась. Пусть удача будет на вашей стороне.")},
						{message: SimpleMessage("Колесо фортуны крутится...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Ну что, паника или спокойствие?")},
						{message: SimpleMessage("Пистолет уже в игре...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Время узнать, кто сегодня проиграл.")},
						{message: SimpleMessage("Палец на спусковом курке...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Готовы к самому страшному клику в вашей жизни?")},
						{message: SimpleMessage("Курок нажат...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Сейчас всё решит один выстрел.")},
						{message: SimpleMessage("Тишина перед бурей...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Ну что ж, время делать плохие выборы.")},
						{message: SimpleMessage("Барабан медленно вращается...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Возможности передумать нет.")},
						{message: SimpleMessage("Щёлк...")},
					},
				},
				{
					allOf: []oneOf{
						{message: SimpleMessage("Все готовы? Тогда судьба начинает отсчёт.")},
						{message: SimpleMessage("Револьвер идёт по кругу...")},
					},
				},
			},
		},
		"gunslinger killed": {
			oneOf: []oneOf{
				{message: SimpleMessage("Раздался выстрел — и %gunslinger больше не с нами")},
				{message: SimpleMessage("Барабан провернулся, курок щёлкнул... %gunslinger выбывает")},
				{message: SimpleMessage("Пуля нашла свою жертву — это был %gunslinger")},
				{message: SimpleMessage("Кровь, порох и тишина... %gunslinger проиграл")},
				{message: SimpleMessage("%gunslinger решил, что жил слишком долго")},
				{message: SimpleMessage("В этот раз не повезло %gunslinger")},
				{message: SimpleMessage("На этот раз смерть выбрала %gunslinger")},
				{message: SimpleMessage("Роковой выстрел для %gunslinger")},
				{message: SimpleMessage("%gunslinger больше не ответит")},
				{message: SimpleMessage("Прощай, %gunslinger, мы тебя запомним...")},
				{message: SimpleMessage("Игра окончена для %gunslinger")},
				{message: SimpleMessage("Момент истины для %gunslinger оказался последним")},
				{message: SimpleMessage("%gunslinger получил билет в один конец.")},
				{message: SimpleMessage("Удача отвернулась от %gunslinger.")},
				{message: SimpleMessage("Сегодня револьвер выбрал %gunslinger.")},
				{message: SimpleMessage("Не повезло. Совсем не повезло. Особенно %gunslinger.")},
				{message: SimpleMessage("Статистика пополнилась именем %gunslinger.")},
				{message: SimpleMessage("%gunslinger оказался не тем счастливчиком.")},
				{message: SimpleMessage("Похоже, шанс 1 к N всё-таки сработал для %gunslinger.")},
			},
		},
		"killed by atomic bullet": {
			oneOf: []oneOf{
				{message: SimpleMessage("Щёлк — и внезапно комната превратилась в эпицентр ядерного гриба. В револьере оказалась атомная пуля")},
				{message: SimpleMessage("...от группы смельчаков остался только радиоактивный след. Видимо, кто-то подсунул в барабан не ту пулю")},
				{message: SimpleMessage("Комната наполнилась ярким светом... Все игроки мгновенно испарились. Кто-то явно жульничал с боеприпасами")},
				{message: SimpleMessage("Кто-то перепутал револьвер с оружием массового поражения. Выживших нет. Добиты.")},
				{message: SimpleMessage("Кажется, это была не совсем обычная пуля. Совсем не обычная.")},
				{message: SimpleMessage("Револьвер неожиданно стал причиной локального апокалипсиса.")},
				{message: SimpleMessage("Победителей нет. Только радиоактивный пепел.")},
			},
		},
		"joined the game":       {message: SimpleMessage("Участники игры %date")},
		"game join list item":   {message: SimpleMessage("%num. %gunslinger")},
		"owner of the game":     {message: SimpleMessage("владелец")},
		"shot in game":          {message: SimpleMessage("выбыл")},
		"top is not determined": {message: SimpleMessage("Пока что мы не можем составить топ игроков")},
		"top players by games":  {message: SimpleMessage("Топ-%number выбывших игроков:")},
		"top game player": {message: PluralMessage{
			one:  "%i. %user - %times раз",
			few:  "%i. %user - %times раза",
			many: "%i. %user - %times раз",
		}},
		"available only in chat": {message: SimpleMessage("Русская рулетка игра не для одного")},
		"player already in game": {
			oneOf: []oneOf{
				{message: SimpleMessage("Ты уже в игре. Смерть тебя уже запомнила")},
				{message: SimpleMessage("Жаждешь смерти? Подожди своей очереди")},
				{message: SimpleMessage("Ты уже в списке на расстрел. Терпение.")},
				{message: SimpleMessage("Ты уже в деле. Расслабься и жди выстрела.")},
				{message: SimpleMessage("Ты уже участвуешь. Или передумал?")},
				{message: SimpleMessage("Смерть любит нетерпеливых")},
				{message: SimpleMessage("Ты уже в игре, не торопи смерть")},
				{message: SimpleMessage("Один раз в игре - достаточно для проверки удачи")},
				{message: SimpleMessage("Ты уже в списке потенциальных покойников")},
				{message: SimpleMessage("Не волнуйся, про тебя никто не забыл.")},
				{message: SimpleMessage("Ты уже держишь место в очереди к револьверу.")},
				{message: SimpleMessage("Одного билета в эту игру вполне достаточно.")},
			},
		},
		"player is not kicked": {
			oneOf: []oneOf{
				{message: SimpleMessage("Револьвер заклинило. Видимо, у кого-то иммунитет")},
				{message: SimpleMessage("Порох отсырел — приговор не был приведён в исполнение")},
				{message: SimpleMessage("Смерть сегодня капризничает. Кое-кто временно неуязвим")},
				{message: SimpleMessage("Казнь откладывается — технические неполадки.")},
				{message: SimpleMessage("Кто-то подложил холостой патрон")},
				{message: SimpleMessage("Сегодня удача оформила кому-то отпуск от смерти.")},
				{message: SimpleMessage("Револьвер недовольно щёлкнул и передумал.")},
				{message: SimpleMessage("Похоже, сегодня судьба решила дать отсрочку.")},
				{message: SimpleMessage("Даже смерть иногда промахивается.")},
				{message: SimpleMessage("Не сегодня.")},
			},
		},
		"wait for game timeout": {
			oneOf: []oneOf{
				{message: SimpleMessage("Дайте барабану остыть после последнего выстрела")},
				{message: SimpleMessage("Смерть тоже любит делать перерывы, не спешите")},
				{message: SimpleMessage("Подождите, пока духи прошлых игроков разойдутся")},
				{message: SimpleMessage("Дайте нам время замести следы от прошлой игры")},
				{message: SimpleMessage("Мы наделали слишком много шума, пока нам нужно залечь на дно")},
				{message: SimpleMessage("Смерть пока занята другими")},
				{message: SimpleMessage("Следующая партия скоро начнётся. Терпим.")},
				{message: SimpleMessage("Фортуна ушла на перекур.")},
				{message: SimpleMessage("Револьвер пока на техническом обслуживании.")},
			},
		},
		"active game not found":                  {message: SimpleMessage("Ещё никто не начал игру")},
		"user game statistics":                   {message: SimpleMessage("Вы участвовали в %games игре(-ах) и проиграли %shots раз(а)")},
		"available settings below":               {message: SimpleMessage("Персонализируйте игру используя перечисленные ниже опции")},
		"settings can be changed only by admins": {message: SimpleMessage("Изменять настройки игры могут только администраторы чата")},
		"4 shot revolver":                        {message: SimpleMessage("Colt Cloverleaf - 4 игрока")},
		"5 shot revolver":                        {message: SimpleMessage("S&W Model 642 - 5 игроков")},
		"6 shot revolver":                        {message: SimpleMessage("Colt Python - 6 игроков")},
		"7 shot revolver":                        {message: SimpleMessage("Наган - 7 игроков")},
		"8 shot revolver":                        {message: SimpleMessage("S&W Model 627 PC - 8 игроков")},
		"9 shot revolver":                        {message: SimpleMessage("Diamondback Sidekick - 9 игроков")},
		"revolver has been replaced": {message: PluralMessage{
			one:  "Теперь в игре может участвовать %i игрок",
			few:  "Теперь в игре могут участвовать %i игрока",
			many: "Теперь в игре могут участвовать %i игроков",
		}},
		"settings will be applied for next games": {message: SimpleMessage("Изменения вступят в силу со следующего раунда")},
		"proof link":      {message: SimpleMessage("<a href=\"%url\">🔐 Источник случайности</a>")},
		"game log header": {message: SimpleMessage("Последние %number игр:")},
		"game log item":   {message: SimpleMessage("%date - %username")},
	},
}
