name: Publish

on:
    push:
        branches: ['master']
    release:
        types: ['published']

env:
    GO111MODULE: on

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21
            - name: Verify dependencies
              run: go mod verify
            - name: Install dependencies
              run: go mod vendor
            - name: Build
              run: go build -v ./...
            - name: Run go vet
              run: go vet ./...
            - name: Run go test
              run: go test ./...
    push:
        needs: test
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/amd64,linux/arm64
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build & Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: taranovegor/naganbot:latest
                  platforms: linux/amd64,linux/arm64
